name: 'Fetch Assembly version '
description: 'Get assembly version from a dotnet project'
inputs:
  project-path:
    description: 'path to search *.csproj file'
    requires: true
    type: string
    
outputs:
  assembly-version: 
    description: 'Project assembly version'
    value: ''
  major:
    description: 'Major identifier'
    value: ''
  minor:
    description: 'Minor identifier'
    value: ''
  revision:
    description: 'Revision identifier'
    value: ''
  build:
    description: 'Build identifier'
    value: ''

runs:
  using: 'node16'
  main: 'index.js'